Fixed some parameter to work with my Danfoss Air
JonasPed/pydanfoss-air pull request #5
Opened 2024-10-29 20:35 UTC by mschlappa

Can you verify if it works for you too?

Greetings Marcus

2024-10-29 20:37 UTC, mschlappa commented
Oh. I have to check "boost" command before merge. Stand by ;-)

2024-10-29 20:46 UTC, mschlappa commented
Hi @JonasPed1 Now you can check the PR.

2024-10-30 07:47 UTC, mschlappa commented
The last fix (2 commits) was a nasty one.  automatic_bypass read output was inverted and the command too :-)

2024-10-30 15:36 UTC, JonasPed commented
Interresting that there aparrently are different implementations. I will try to test it against my unit in a couple of days.

2024-10-30 15:48 UTC, mschlappa commented
Thank you!

I found another small issue in the homeassistant Integration regarding the automatic_bypass switch. But I couldn’t test it yet.

It looks like there is an duplication of the bypass command where I would expect the automatic_bypass command

[=> diff](https://github.com/home-assistant/core/compare/dev...mschlappa:core:dev?diff=split&w=)

2024-11-03 21:00 UTC, JonasPed requested changes
I have added a couple of comments. Please see below for the output before and after your changes. 

*Before changes* 
```
(venv) jonas@asterix-kubuntu:~/development/pydanfossair/pydanfoss-air (master)$ python -m pydanfossair --host <HOSTNAME>
ReadCommand.exhaustTemperature: 12.82
ReadCommand.supplyTemperature: 19.9
ReadCommand.extractTemperature: 20.62
ReadCommand.outdoorTemperature: 11.6
ReadCommand.roomTemperature: 21.01
ReadCommand.roomTemperatureCalculated: 20.29
ReadCommand.humidity: 54.11764705882353
ReadCommand.bypass: False
ReadCommand.filterPercent: 21.96078431372549
ReadCommand.boost: False
ReadCommand.supply_fan_speed: 1214
ReadCommand.exhaust_fan_speed: 1611
ReadCommand.fan_step: 40
ReadCommand.away_mode: False
ReadCommand.battery_percent: 0.0
ReadCommand.automatic_bypass: True
ReadCommand.operation_mode: program
```

*After changes*
```
(venv) jonas@asterix-kubuntu:~/development/pydanfossair/pydanfoss-air (mschlappa/master)$ python -m pydanfossair --host <HOSTNAME>
ReadCommand.exhaustTemperature: 12.92
ReadCommand.supplyTemperature: 19.97
ReadCommand.extractTemperature: 20.67
ReadCommand.outdoorTemperature: 11.7
ReadCommand.roomTemperature: 20.99
ReadCommand.roomTemperatureCalculated: 20.31
ReadCommand.humidity: 54.509803921568626
ReadCommand.bypass: False
ReadCommand.filterPercent: 21.96078431372549
ReadCommand.boost: False
ReadCommand.supply_fan_speed: 1242
ReadCommand.exhaust_fan_speed: 1612
ReadCommand.fan_step: 4
ReadCommand.away_mode: False
ReadCommand.battery_percent: 0.0
ReadCommand.automatic_bypass: False
ReadCommand.operation_mode: program
```

2024-11-03 21:00 UTC, JonasPed commented on pydanfossair/danfossclient.py
> +            return_value = self._read_bit(command, socket)
It looks like the response is inverted on my unit now.

2024-11-03 21:00 UTC, JonasPed commented on pydanfossair/commands.py
> +    fan_step = bytes([0x01, 0x04, 0x15, 0x61])
The fan step is now a step between 1 and 10 and not the percentage of full speed (between 10 and 100).

2024-11-03 21:00 UTC, JonasPed commented on pydanfossair/commands.py
> +    automatic_bypass_activate = bytes([0x01, 0x06, 0x17, 0x06, 0x01])
I think automatic bypass is inverted now. Reading out all the data from the unit it says "disable automatic bypass", so I will assume that it must be set to true if it should be disabled.

2024-11-04 20:09 UTC, mschlappa commented on pydanfossair/danfossclient.py
> +            return_value = self._read_bit(command, socket)
You are right. I reverted the change.

2024-11-04 20:11 UTC, mschlappa commented on pydanfossair/commands.py
> +    automatic_bypass_activate = bytes([0x01, 0x06, 0x17, 0x06, 0x01])
You are right. I reverted the change.

2024-11-04 20:15 UTC, mschlappa commented on pydanfossair/danfossclient.py
> +            return_value = self._read_byte(command, socket) * 10
I multiplied the step with 10 so that it represents percentage again

2024-11-13 19:54 UTC, merged

2024-11-13 19:55 UTC, JonasPed commented
Thanks for the PR.

2024-11-13 20:32 UTC, mschlappa commented
Thank you for integrating my PR !!
Did you have a chance to look into this small change?
Maybe it can also integrated in the next Release of HA if you agree on it?

> 
> I found another small issue in the homeassistant Integration regarding the automatic_bypass switch. But I couldn’t test it yet.
> 
> It looks like there is an duplication of the bypass command where I would expect the automatic_bypass command
> 
> [=> diff](https://github.com/home-assistant/core/compare/dev...mschlappa:core:dev?diff=split&w=)

Greetings!
Marcus